name: Deploy Corporate Site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Checkout hugo-templates
        uses: actions/checkout@v4
        with:
          repository: info-tech-io/hugo-templates
          token: ${{ secrets.PAT_TOKEN }}
          path: hugo-templates

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.0'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Hugo Templates Factory
        working-directory: hugo-templates
        run: |
          # Copy entire docs directory as module content
          cp -r ../docs ./module-content

          # Install dependencies
          npm install

          # Make build script executable
          chmod +x scripts/build.sh

          # Build using module.json configuration
          scripts/build.sh --config ./module-content/module.json --output ./dist

      - name: Verify build output
        run: |
          echo "Build output structure:"
          ls -la hugo-templates/dist/
          echo "Index file check:"
          if [ -f "hugo-templates/dist/index.html" ]; then
            echo "✅ Index file exists"
            head -10 hugo-templates/dist/index.html
          else
            echo "❌ Index file missing"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: hugo-templates/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4